JobApp/urls.py
from django.urls import path,re_path
from JobApp import views
from django.views.generic import RedirectView
app_name='JobApp'

urlpatterns = [
    
    path('import_jobs/', views.import_jobs, name='import_jobs'),
    path('', views.job_view, name='job_view'), # if using class based view, views.job_view.as_view()
    path('job-details/<int:job_id>/', views.job_details, name='job_details'),
    path('single_job_view/<int:id>/', views.single_job_view, name='single_job_view'),
    path('apply_job_view/<int:id>/', views.apply_job_view, name='apply_job'),
    path('post_resume', views.post_resume, name='post_resume'),
    path('bookmark_view/<int:id>/', views.bookmark_view, name='bookmark_view'),
    path('create_job/', views.create_job, name='create_job'),
    path('search_job/', views.search_job, name='search_job'),
    path('do_comment/<int:id>/', views.do_comment, name='do_comment'),
    path('likes/<int:id>/',views.like_view,name='likes'),

    # path('commentView/', views.Comments_view.as_view(), name='comment'),
    # path('comment/<int:pk>', views.Comments_view.as_view(), name='comment'),   # get single record 
    # path('comment/<int:id>/', views.comment, name='Commit'),

    



    

    path('dashboard_view/', views.dashboard_view, name='dashboard_view'), 
    path('dashboard/employer/edit_job/<int:id>', views.edit_job, name='edit_job'),
    path('dashboard/employer/delete_job/<int:id>', views.delete_job, name='delete_job'),
    path('dashboard/employer/close/<int:id>', views.make_close_job, name='make_close_job'),
    path('dashboard/employer/delete_bookmark/<int:id>', views.delete_bookmark, name='delete_bookmark'),
    path('dashboard/employer/applicant_details/<int:id>', views.applicant_details, name='applicant_details'),
    path('dashboard/employer/applicants_list/<int:id>', views.applicants_list, name='applicants_list'),


    path('recruiter_job_view/', views.recruiter_job_view, name='recruiter_job_view'),
    path('about_us/', views.about_us, name='about_us'), 
    path('contact_us/', views.contact_us, name='contact_us'), 
    path('custom_csrf_failure/',views.custom_csrf_failure), 
]

job_portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from JobApp.views import job_view 


urlpatterns = [
    path('', job_view, name='job_view'),
    path('admin/', admin.site.urls),
    path('Account/',include('Account.urls')),
    path('JobApp/',include('JobApp.urls')),
    path('',include('jsonApp.urls')),
    path('__reload__/',include('django_browser_reload.urls')),

    
     # Redirect the root URL to the admin page
    
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

JobApp/models.py
from users.models import CustomUser 
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.utils import timezone


status_choices=(('apl','applied'),('intw','intervew'),('hrd','hired'),('rjct','rejected'),)
gender_chioce=(( "m","male"
    
),('f','female'),)
WORK_MODE_CHOICES = (('REMOTE', 'Remote'),
        ('Onsite', 'Onsite'),
        ('Hybrid', 'Hybrid'),)
language= (('eng','English Language'),
('fran',"Franch Language"),('urdu','Urdu Language'),)

education= (('high_school', 'High School'),
        ('bachelors', 'Bachelor\'s Degree'),
        ('masters', 'Master\'s Degree'),
        ('phd', 'PhD'),
        ('other', 'Other'),)
shift= (('morning','Morning Shift'),
('evening','Evening Shift'),)      


# class for Technical skill
class Skill(models.Model):
    skill_name=models.CharField(_("skill"), max_length=200)
    def __str__(self):
             return self.skill_name

class Job(models.Model):
    
    recruiter = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        limit_choices_to={'user_type': 'recruiter'}
    )
   
    title = models.CharField(max_length=255)
    description = models.TextField()
    location = models.CharField(max_length=255)
    job_type = models.CharField(
        max_length=50,
        choices=[
            ('full-time', 'Full-time'),
            ('part-time', 'Part-time'),
            ('internship', 'Internship')
        ]
    )
    salary = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True
    )
    skills =models.ManyToManyField("Skill", related_name='technical_skill',blank=True)
    requirements = models.TextField(help_text="List of job requirements")
    experience_required = models.CharField(
        max_length=100,
        help_text="Required experience level"
    )
    specifications = models.TextField(
        null=True,
        blank=True,
        help_text="Any other specific requirements"
    )
    education=models.CharField(_("Education"), max_length=50,choices=education, default='masters')
    language=models.CharField(_("Languages"), max_length=50,choices=language,default='eng')
    schedule=models.CharField(_("Shift and schedule"), max_length=50,choices=shift,default='morning')
    work_mode = models.CharField(
        max_length=10, 
        choices=WORK_MODE_CHOICES, 
        default='Onsite',  # Default to 'Onsite'
    )
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    is_published = models.BooleanField(default=False)
    is_closed = models.BooleanField(default=False)
    Vacancy = models.CharField(max_length=10, null=True)
    end_date = models.DateField(max_length=20, null=True,default='None')
    gender = models.CharField(max_length=30,choices=gender_chioce ,blank=True)
    likes=models.ManyToManyField(CustomUser,related_name='job_likes')

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title

class JobApplication(models.Model):
    candidate=models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    job_id=models.CharField( max_length=50)
    job_title=models.CharField(_("job Title"), max_length=50)
    status=models.CharField(max_length=50, choices=status_choices,default='apl')
    applied_on=models.DateTimeField(_("Applied DateTime"), auto_now_add=True)  
    
    def __str__(self):
        return f"{self.candidate.email} applied for {self.job_id} at {self.applied_on}"
    
class Applicant(models.Model):
    user= models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    job= models.ForeignKey(Job, on_delete=models.CASCADE)
    timestamp=models.DateTimeField(auto_now_add=True)  

    def __str__(self):
        return f"{self.job.title}  {self.user}"

class BookmarkJob(models.Model):
    user= models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    job=models.ForeignKey(Job, on_delete=models.CASCADE)
    timestamp=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _("Bookmark")
        verbose_name_plural = _("Bookmarks")

    
    def __str__(self):
       return f"Bookmark by {self.user.email} for {self.job.title}"

    
class Contact(models.Model):

    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    def __str__(self):
        return self.name

# model to create resume
class Resume(models.Model):
    # Choices for title
    TITLE_CHOICES = [
        ("Software Developer", "Software Developer"),
        ("Data Analyst", "Data Analyst"),
        ("Project Manager", "Project Manager"),
        ("UI/UX Designer", "UI/UX Designer"),
        ("Other", "Other"),
    ]

    # Choices for education
    EDUCATION_CHOICES = [
        ("High School", "High School"),
        ("Associate Degree", "Associate Degree"),
        ("Bachelor's Degree", "Bachelor's Degree"),
        ("Master's Degree", "Master's Degree"),
        ("Ph.D.", "Ph.D."),
    ]

    # Choices for experience level
    EXPERIENCE_CHOICES = [
        ("Entry Level", "Entry Level (0-2 years)"),
        ("Mid Level", "Mid Level (2-5 years)"),
        ("Senior Level", "Senior Level (5+ years)"),
    ]
    SKILLS_CHOICES = [
    ("Python", "Python"),
    ("Django", "Django"),
    ("JavaScript", "JavaScript"),
    ("React", "React"),
    ("HTML", "HTML"),
    ("CSS", "CSS"),
    ("SQL", "SQL"),
    ("Java", "Java"),
    ("C++", "C++"),
    ("Other", "Other"),
   ]

    username = models.OneToOneField(
        CustomUser,  # Use your custom user model here if applicable
        on_delete=models.CASCADE,
        related_name="resume"
    )
    title = models.CharField(
        max_length=50,
        choices=TITLE_CHOICES,
        default="Other",
        help_text="Title of the resume. Choose the most appropriate role."
    )
    objective = models.TextField(
        max_length=1000,
        help_text="A short paragraph about the candidate's career objectives and aspirations."
    )
    skills = models.ManyToManyField('Skill',
    max_length=255,
    
    default="Java",
    help_text="Select a key skill. Add multiple skills by creating separate entries.")
    experience = models.CharField(
        max_length=50,
        choices=EXPERIENCE_CHOICES,
        default="Entry Level",
        help_text="Select the experience level of the candidate."
    )
    education = models.CharField(
        max_length=50,
        choices=EDUCATION_CHOICES,
        default="Bachelor's Degree",
        help_text="Select the highest level of education attained."
    )
    certifications = models.TextField(
        blank=True,
        help_text="Details of certifications or training. Use JSON or plain text for multiple entries."
    )
    achievements = models.TextField(
        blank=True,
        help_text="List of notable achievements or awards. Use JSON or plain text."
    )
    projects = models.TextField(
        blank=True,
        help_text="Summary of significant projects with details. Use JSON or plain text."
    )
    resume_file = models.FileField(
        upload_to="resumes/",
        blank=True,
        null=True,
        help_text="Upload a PDF or document version of the resume."
    )
    linkedin_profile = models.URLField(
        blank=True,
        help_text="URL to the candidate's LinkedIn profile."
    )
    portfolio_website = models.URLField(
        blank=True,
        help_text="URL to the candidate's portfolio or personal website."
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.username}'s Resume"
    

# Comment Model 
class CommentModel(models.Model):
    user=models.ForeignKey(CustomUser, related_name='comments', on_delete=models.CASCADE)
    job= models.ForeignKey('Job', related_name='job', on_delete=models.CASCADE)
    comment = models.TextField()
    created_at=models.DateTimeField( auto_now_add=True)

# Like Model 
# class LikeModel(models.Model):
#     user=models.ForeignKey(CustomUser, related_name='user', on_delete=models.CASCADE)
#     job= models.ForeignKey('Job', related_name='job', on_delete=models.CASCADE)
#     like = models.TextField()
#     created_at=models.DateTimeField( auto_now_add=True)    
        
    

JobApp/forms.py
from django import forms
from django.forms.widgets import CheckboxSelectMultiple

from django.contrib.auth.forms import UserCreationForm 
from users.models import  CustomUser
from JobApp.models import Job ,Applicant ,BookmarkJob ,Contact,Resume,CommentModel


#create form for create_job 
class JobForm(forms.ModelForm):
    
    class Meta:
        model=Job
        exclude=['recruiter','likes']


class JobApplyForm(forms.ModelForm):
    
    class Meta:
        model = Applicant
        fields = ("job",)

class BookmarkJobForm(forms.ModelForm):
    
    class Meta:
        model = BookmarkJob
        fields = ("job",)

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
# form to do_comment
class CommentForm(forms.ModelForm):
    class Meta:
        model=CommentModel
        fields='__all__'
    
        

# django form for post_resume
class ResumeForm(forms.ModelForm):
    
    class Meta:
        model = Resume
        # fields = '__all__'
        exclude=('username',)   
        
        widgets = {
            'skills': CheckboxSelectMultiple(),  # Render skills as checkboxes
         }

        def __init__(self, *args, **kwargs):
            super(ResumeForm, self).__init__(*args, **kwargs)

            # Add classes to form fields for better styling
            for field_name, field in self.fields.items():
                if isinstance(field.widget, forms.TextInput):
                    field.widget.attrs['class'] = 'form-control'
                elif isinstance(field.widget, forms.Textarea):
                    field.widget.attrs['class'] = 'form-control'
                    field.widget.attrs['rows'] = 4
                elif isinstance(field.widget, forms.Select):
                    field.widget.attrs['class'] = 'form-control'
                elif isinstance(field.widget, forms.FileInput):
                    field.widget.attrs['class'] = 'form-control-file' 
    
        

    

   

templates/JobApp/applicants_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-hero overlay inner-page bg-image" style="background-image: url(/static/images/hero_4.jpg);" 
    id="home-section">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1 class="text-white font-weight-bold">All Applicants </h1>
                <div class="custom-breadcrumbs">
                    {% comment %} <a href="{% url 'JobApp:home' %}">Home</a> <span class="mx-2 slash">/</span> {% endcomment %}
                    <a href="{% url 'JobApp:dashboard_view' %}">Dashboard</a> <span class="mx-2 slash">/</span>
                    <span class="text-white"><strong>All Applicants </strong></span>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card">
                    <h5 class="card-header text-center mb-5"> All Applicants </h5>
                    <div class="table-responsive">
                        <table class="table text-center">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Name</th>
                                    <th>Job Title</th>
                                    <th>Applied Date</th>
                                    <th>View </th>
                        
                                </tr>
                            </thead>
                            <tbody>
                                {% for applicant in all_applicants %}
                        {{ applicant.get_total_applicant }}

                                <tr>
                                    <td class="text-center"><a href="">{{ applicant.user.email }}</a></td     >
                                    <td>{{ applicant.job.title }}</td>
                                    <td>{{ applicant.timestamp }}</td>
                                    <td>
                                        <a class="btn btn-info btn-sm" href="{% url 'JobApp:applicant_details' applicant.user.id %}"
                                                role="button">
                                            Click
                                        </a>
                                    </td> 

                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

{% endblock %}

templates/JobApp/contact_us.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block  title %}Create Job{% endblock  %}
{% block  content %}
{% include "recruiter_navbar.html" %}
<div class="modal fade" id="contactModal" tabindex="-1" aria-labelledby="contactModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="contactModalLabel">Contact Us</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body"> 
                <form id="contactForm" method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="button" class="btn btn-success btn-lg" id="submitContactForm">Submit</button>
                </form>
                <div id="contactResponse" class="mt-2"></div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#submitContactForm').click(function (e) {
            e.preventDefault();
            
            $.ajax({
                data: $('#contactForm').serialize(),
                type: $('#contactForm').attr('method'),
                url: "{% url 'JobApp:contact_us' %}",
                success: function (response) {
                    $('#contactResponse').html(
                        '<div class="alert alert-success">Thank you for reaching out!</div>'
                    );
                    $('#contactForm')[0].reset();  // Clear the form
                },
                error: function (response) {
                    $('#contactResponse').html(
                        '<div class="alert alert-danger">' + response.responseJSON.errors + '</div>'
                    );
                }
            });
        });
    });
</script> 

{% endblock  %}

templates/JobApp/edit_job.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Job Edit Form{% endblock  %}
{% block content %}
<a class="btn btn-info btn-sm "data-toggle='model' data-target='EditJobModal'  role="button">Edit</a>
<div class="modal fade" id="EditJobModal" tabindex="-1" aria-labelledby="EditJobModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="EditJobModalLabel">Edit job</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <div class="modal-body"> 
              <form id="EditJobForm" method="POST">
                  {% csrf_token %}
                  {{ form|crispy }}
                  <button type="button" class="btn btn-success btn-lg" id="submitEditJobForm">Submit</button>
              </form>
              <div id="jobResponse" class="mt-2"></div>
          </div>
      </div>
  </div>
</div> 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    $('#submitContactForm').click(function (e) {
        e.preventDefault();
        
        $.ajax({
          data: $('#EditJobForm').serialize(),
          type:$('#EditJobForm').attr('method'),
          url:"{% url 'JobApp:edit_job' job.id  %}",
          success: function (response) {
            $('#jobResponse').html(
                '<div class="alert alert-success">You have successfully edit job!</div>'
            );
            $('#EditJobForm')[0].reset();  // Clear the form
        },
        error: function (response) {
            $('#jobResponse').html(
                '<div class="alert alert-danger">' + response.responseJSON.errors + '</div>'
            );
        }

        });
    });
  });  

</script>
{% endblock  %}

templates/JobApp/search_job.html
{% extends "base.html" %} {% load static %} {% block title %} Job
ListPage{% endblock %} {% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />

<!-- Load css fils  -->
<link rel="stylesheet" href="{% static 'css/searchbox.css' %}" />
<link rel="stylesheet" href="{% static 'css/jobpage.css' %}">
<link rel="stylesheet" href="{% static 'css/recentSearches.css'%}">
<link rel="stylesheet" href="{% static 'css/dot.css'%}">

{% include "candidate_navbar.html" %} 

<!-- Job Cards -->
<div class="container-fluid">
    <!-- Search box -->
    <div class="row mt-3">
        <form class="search-box" method="post" action="{% url 'JobApp:search_job' %}">
            {% csrf_token %}
            <div class="search-input">
                <i class="fas fa-briefcase"></i>
                <input type="search" name="job" placeholder="Job Title, keywords, or company" id="job" value='{{job_query}}'   />
            </div>
            <div class="divider">|</div>
            <div class="search-input">
                <i class="fas fa-map-marker-alt"></i>
                <input type="search" name="location" placeholder="Location, city, code, 'Remote'" id="location" value='{{location_query}}'/>
            </div>
            <button type="submit" class="find-button">Find find_job</button>
        </form>
        <br />
    </div>
    
    <!-- anchor tag 'find_job for you and recent searches' -->
  
    <hr style="
      border: 1px solid #ccc;
      width: 100%;
      text-align: left;
      
    " />
    
    <div class="row">
        {% if find_job %}
        <!-- Left Side: Job Cards -->
        <div class="col-md-4">
            <!-- Adjusted to 4 columns for the job list -->
        </h6  class='mr-3 text-center'><b> <a href="{% url 'JobApp:post_resume' %}" style="text-decoration: none;">Upload your cv </a>find next job on alibaba</b></h6>

            {% for job in find_job %}
              
            <div class="card shadow-sm mb-3 border border-dark rounded job-item" data-job-id="{{ job.id }}"
                onclick="showJobDetails({{ job.id }})">
                
                <article class="card-body" >
                    <div class="row card-title d-flex justify-content-between font-weight-bold" style="font-size: 16px;">
                        <div class="col-md-6"><b>{{ job.title }} </b></div>
                        <div class="col-md-6 text-right" onclick="showBox('buttonBox{{ forloop.counter }}')" >
                            <i class="fa-solid fa-ellipsis-vertical" ></i>
                            <!-- Hidden div for buttons -->
                            <div class="button-box" id="buttonBox{{ forloop.counter }}">
                                <button>
                                    <a style="text-decoration: none;" class="bg-black" href="{% url 'JobApp:bookmark_view' job.id %}"><i class="fa-solid fa-bookmark"></i> Save Job</a> 
                                </button>
            
                                <!-- Second button: Report a problem with the job -->
                                <button>
                                    <a style="text-decoration: none;" href=""><i class="fa-sharp fa-solid fa-flag"></i> Is there a problem with this job?</a>
                                </button>
                            </div>
                        </div>
                    </div>
                    <!-- <h4 class="card-title"><b>{{ job.title }}</b></h4> -->
                    <h6>{{ job.recruiter.recruiterprofile.company_name }}</h6>
                    {% comment %}
                    <p class="card-text">{{ job.description|truncatewords:10 }}</p>
                    {% endcomment %}
                    <h6>{{ job.location }}</h6>
                    
                
                    <div class="job-details-row mb-2 p-1" style='font-size:14px; '>
                        <div class="job-detail p-1" style="background-color: #4da6ff">
                            <i class="fa-solid fa-briefcase"></i> {{ job.get_job_type_display }}
                        </div>
                        
                        <div class="job-detail p-1">{{ job.get_schedule_display }}</div>

                        <div class="job-detail p-1">
                            ₹ {{ job.salary|default:"Not specified" }} per year
                        </div>
                    </div>

                    <p class="mb-1">
                        <strong>Experience Required:</strong> {{ job.experience_required }}
                    </p>

                    <div class="row m-1 mb-3 d-flex justify-content-between">
                        <a href="{% url 'JobApp:single_job_view' job.id %}"
                            style="text-decoration: none; color: black"><i class="fa-solid fa-paper-plane"></i> Easily
                            apply</a>
                        <!-- <a href="" class="btn btn-dark">Visit Job</a> -->
                    </div>
                    
                    {% if postdays == 0 %}
                    <p>just post</p>
                    {% elif postdays == 1%}

                    <p>posted {{ postdays }} day ago</p>
                    {% else %}
                    <p>posted {{ postdays }} days ago</p>
                    {% endif %}

                    {% if job.skills_list %}
                            {% for skill in job.skills_list %}
                                <span class="text-muted">{{ skill.skill_name }}{% if not forloop.last %}, {% endif %}</span>
                            {% endfor %}
                            <span>.....</span>
                        {% else %}
                            <p><b>No specific skills mentioned.</b></p>
                        {% endif %}
                </article>
            </div>
            {% endfor %}
        </div>
        <div class="col-md-8">
            <!-- Right Side: Job Details -->
            <div id="job-details-container" class='main-div'>
                <div class="fixed-div " >
                    <h3 style="font-weight: bold;">{{ find_job.0.title }}</h3>
                    <!-- Default to the first job's details -->
                    <h6 style="font-weight: bold;">{{ find_job.0.recruiter.recruiterprofile.company_name }}</h6>
                    <h6 style="font-weight: bold;">{{ find_job.0.location }}</h6>
                    <h6 style="font-weight: bold;" class="" style="background-color: #b3cccc;"></h6>₹ {{ find_job.0.salary|default:"Not specified" }}
                    per
                    year
                </div>
                <div class="scrollable-div">
                    <h3 style="font-weight: bold;">Full Job description</h3>  
                    <p>{{ find_job.0.description }}</p>

                    <p><strong>Location:</strong> {{ find_job.0.location }}</p>
                    <p>
                        <i class="fa-solid fa-briefcase"></i> <strong>Job Type:</strong> {{ find_job.0.get_job_type_display }}
                    </p>
                    <p>
                        <strong>Salary</strong>₹ {{ find_job.0.salary|default:"Not specified" }} per year
                    </p>
                    <p>
                        <strong>Experience Required:</strong> {{ find_job.0.experience_required }}
                    </p>
                    <p><strong>Education:</strong> {{ find_job.0.get_education_display }}</p>
                    <p><strong>Languages:</strong> {{ find_job.0.get_language_display }}</p>

                    <p><strong>Shift and Schedule:</strong> {{ find_job.0.get_schedule_display }}</p>
                    <p><strong>Work Mode:</strong> {{ find_job.0.get_work_mode_display }}</p>
                    <p>
                        <strong>Requirements:</strong> {{ find_job.0.requirements|linebreaksbr }}
                    </p>
                    {% if find_job.0.specifications %}
                    <p>
                        <strong>Specifications:</strong> {{ find_job.0.specifications|linebreaksbr }}
                    </p>
                    {% endif %}
                    <p>
                        <strong>vacancy:</strong> {{ find_job.0.Vacancy|default:"Not specified" }}
                    </p>
                </div>
            </div>
            <div class="row p-1 m-1 d-flex justify-content-between">
                <a href="{% url 'JobApp:single_job_view' find_job.0.id %}" class="btn btn-primary">Apply Job</a>
            </div>
        </div>
    </div>

{% elif not find_job %}
            <div class="no-job-message m-auto text-center">
                <p class ="text-center">🚀 Oops! No jobs match your search criteria.</p>
                <p>Try searching with different keywords or check back later for new job postings.</p>
                <a href="{% url 'JobApp:job_view' %}" class="btn btn-primary " >View All Jobs</a>
            </div>
{% endif %}
</div>
<!-- Footer -->
<footer class="bg-light footer text-center fixed-bottom">
    <p>&copy; 2024 Job Portal. All Rights Reserved.</p>
</footer>

<!-- JavaScript to handle job clicks -->
<script>
    function showJobDetails(jobId) {
        fetch(`/job-details/${jobId}/`)
            .then(response => response.json())
            .then(data => {
                const detailsContainer = document.getElementById('job-details-container');
                detailsContainer.innerHTML = `
                  <h3>${data.title}</h3>
                  <p>${data.recruiter.recruiterprofile.company_name}</p>
                  <p>${data.description}</p>
                  <p><strong>Location:</strong> ${data.location}</p>
                  <p><strong>Job Type:</strong> ${data.job_type}</p>
                  <p><strong>Salary:</strong>₹ {{ find_job.0.salary|default:"Not specified" }} per year</p>
                  <p><strong>Experience Required:</strong> ${data.experience_required}</p>
                  <p><strong>Education:</strong> ${data.education}</p>
                  <p><strong>Languages:</strong> ${data.language}</p>
                  <p><strong>Shift and Schedule:</strong> ${data.schedule}</p>
                  <p><strong>Work Mode:</strong> ${data.work_mode}</p>
                  <p><strong>Requirements:</strong> ${data.requirements}</p>
                  ${data.specifications ? `<p><strong>Specifications:</strong> ${data.specifications}</p>` : ''}
                  <p><strong>Vacancy:</strong> ${data.Vacancy || 'Not specified'}</p>

              `;
            });
    }

    // Optionally, display the first job's details by default when the page loads
    document.addEventListener("DOMContentLoaded", function () {
        showJobDetails({{ find_job.0.id }});  // First job as default
  });
</script>
<!-- Script for slide anchor tag 'find_job for you and recent searches' -->
<script>
    function activate(element) {
      // Remove 'active' class from all nav items<i class="fa-solid fa-ellipsis-vertical" onclick="showBox('buttonBox{{ forloop.counter }}')"></i>
      document.querySelectorAll('.nav-item').forEach(item => {
        item.classList.remove('active');
      });

      // Add 'active' class to the clicked element
      element.classList.add('active');
    }
  </script>
 <!-- script for dots in job card -->
  <script>
    // Function to display the button box near the ellipsis icon
    function showBox(id) {
        const buttonBox = document.getElementById(id);
    
        // Toggle display property on each click
        if (buttonBox.style.display === 'none' || buttonBox.style.display === '') {
            buttonBox.style.display = 'block'; // Show the box
        } else {
            buttonBox.style.display = 'none'; // Hide the box
        }
    }
    

</script>
{% endblock %}