JobApp/urls.py
from django.urls import path,re_path
from JobApp import views
from django.views.generic import RedirectView
app_name='JobApp'

urlpatterns = [
    
    path('import_jobs/', views.import_jobs, name='import_jobs'),
    path('', views.job_view, name='job_view'), # if using class based view, views.job_view.as_view()
    path('job-details/<int:job_id>/', views.job_details, name='job_details'),
    path('single_job_view/<int:id>/', views.single_job_view, name='single_job_view'),
    path('apply_job_view/<int:id>/', views.apply_job_view, name='apply_job'),
    path('post_resume', views.post_resume, name='post_resume'),
    path('bookmark_view/<int:id>/', views.bookmark_view, name='bookmark_view'),
    path('create_job/', views.create_job, name='create_job'),
    path('search_job/', views.search_job, name='search_job'),
    path('do_comment/<int:id>/', views.do_comment, name='do_comment'),
    path('likes/<int:id>/',views.like_view,name='likes'),

    # path('commentView/', views.Comments_view.as_view(), name='comment'),
    # path('comment/<int:pk>', views.Comments_view.as_view(), name='comment'),   # get single record 
    # path('comment/<int:id>/', views.comment, name='Commit'),

    



    

    path('dashboard_view/', views.dashboard_view, name='dashboard_view'), 
    path('dashboard/employer/edit_job/<int:id>', views.edit_job, name='edit_job'),
    path('dashboard/employer/delete_job/<int:id>', views.delete_job, name='delete_job'),
    path('dashboard/employer/close/<int:id>', views.make_close_job, name='make_close_job'),
    path('dashboard/employer/delete_bookmark/<int:id>', views.delete_bookmark, name='delete_bookmark'),
    path('dashboard/employer/applicant_details/<int:id>', views.applicant_details, name='applicant_details'),
    path('dashboard/employer/applicants_list/<int:id>', views.applicants_list, name='applicants_list'),


    path('recruiter_job_view/', views.recruiter_job_view, name='recruiter_job_view'),
    path('about_us/', views.about_us, name='about_us'), 
    path('contact_us/', views.contact_us, name='contact_us'), 
    path('custom_csrf_failure/',views.custom_csrf_failure), 
]

condidates/urls.py
from django.urls import path
from condidates import views
app_name='condidates'

urlpatterns = [
    
    path('signup/',views.registration_view,name='singup'),
    path('signin/',views.login_view,name='signin'),
    path('signout/',views.logout_view,name='signout'),
    path('profile_view/',views.profile_view,name='profile'),
    path('my_profile/',views.my_profile,name='my_profile'),
    
    
    path('custom_csrf_failure/',views.custom_csrf_failure),
   
]

job_portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from JobApp.views import job_view 


urlpatterns = [
    path('', job_view, name='job_view'),
    path('admin/', admin.site.urls),
    path('Account/',include('Account.urls')),
    path('JobApp/',include('JobApp.urls')),
    path('',include('jsonApp.urls')),
    path('__reload__/',include('django_browser_reload.urls')),

    
     # Redirect the root URL to the admin page
    
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

condidates/models.py
from users.models import  CustomUser
from django.utils.translation import gettext_lazy as _
from django.db import models

gender_chioce=(( "m","male"
    
),('f','female'),('oth','Others'),)
status_choices=(('apl','applied'),('intw','intervew'),('hrd','hired'),('rjct','rejected'),)
   # Predefined choices for education
EDUCATION_CHOICES = [
        ('high_school', 'High School'),
        ('bachelors', 'Bachelor\'s Degree'),
        ('masters', 'Master\'s Degree'),
        ('phd', 'PhD'),
        ('other', 'Other'),
    ]
    
    # Predefined choices for experience level
EXPERIENCE_CHOICES = [
        ('0-1', '0-1 Years'),
        ('2-3', '2-3 Years'),
        ('4-5', '4-5 Years'),
        ('6-10', '6-10 Years'),
        ('10+', 'More than 10 Years'),
    ]
 
class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    first_name=models.CharField(_("first_name"),default='xyz', max_length=50)
    last_name=models.CharField(_("last_name"),default='xyz', max_length=50)
    cond_email=models.EmailField(_("Email-address"), max_length=254,unique=True,default="")
    skill= models.CharField(_("Add your skills"), max_length=50,choices=EDUCATION_CHOICES,default='masters')
    experience=models.CharField(_("your work wxperience level"), max_length=50,choices=EXPERIENCE_CHOICES, default='0-1')
    has_resume=models.BooleanField(_("has_resume"),default=True,max_length=5)
    resume=models.FileField(_("Resume"), upload_to='profiles/', max_length=100,blank=True)
    gender=models.CharField(_("Choice "), max_length=50,choices=gender_chioce,default="")
    bio=models.TextField(_("Write your bio here!!!!!!!"),blank=True)
    

    def __str__(self):
        return self.first_name

   
 
class JobApplication(models.Model):
    condidate=models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    job_id=models.CharField( max_length=50)
    job_title=models.CharField(_("job Title"), max_length=50)
    status=models.CharField(max_length=50, choices=status_choices,default='apl')
    applied_on=models.DateTimeField(_("Applied DateTime"), auto_now_add=True)  
    
    def __str__(self):
        return f"{self.condidate.email} applied for {self.job_id} at {self.applied_on}"
    
   

   

condidates/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm 
from users.models import  CustomUser
from condidates.models import UserProfile

#  1. Condidates registration Form
class CondidateRegisteration(UserCreationForm):
    email=forms.EmailField(required=False)
    class Meta:
        model=CustomUser
        fields=['first_name','last_name','email','password1','password2',]
        
        
# 2.  condidates profile form 
class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['user']

    

   

templates/Condidates/ProfileAdd.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
<!-- templates/registration/register.html -->

    
    {% block title %}Profile page{% endblock  %}

    {% block content %}
    {% include "Condidates/navbar.html" %}
    <div class="container-fluid">
        <h2>Profile page</h2>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn-primary" type="submit">submit</button>

        <button class='btn-primary' type="reset">cancel</button>
    </form>
    
    {% if messages %}
        <div class="row">
            <div class="col-md-12">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    </div>
    {% endblock  %}  

templates/Condidates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Job_Portal</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/">Admin</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right mr-1">
        {% if user.is_authenticated %}
            
       
        <li class="nav-item">
            <a href="{% url 'condidates:signout' %}" class="nav-link">{{ request.user }}  logout</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a href="{% url 'condidates:signin' %}" class="nav-link">login</a>
            
        </li>
        {% endif %}

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

templates/Condidates/profilePage.html
<!-- myapp/templates/myapp/profilefile.html -->
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <h1 class="text-center">profilefile Details</h1>
    {% for profile in profiles %}
    <div class="card">
        <div class="card-body">
            <div class="text-center">
                
                
               
                
            </div>
            <h5 class="card-title">{{ profile.first_name }} {{ profile.last_name }}</h5>
            <p class="card-text"><strong>Email:</strong> {{ profile.cond_email }}</p>
            <p class="card-text"><strong>Gender:</strong> {{ profile.get_gender_display }}</p>
            <p class="card-text"><strong>My skills:</strong> {{ profile.skill }}</p>
            <p class="card-text"><strong>My experience:</strong> {{ profile.experience }}</p>

            {% if profile.has_resume %}
                <p class="card-text"><strong>Resume:</strong> <a href="" class="btn btn-primary">Download</a></p>
            {% else %}
                <p class="card-text">No resume uploaded.</p>
            {% endif %}
            <div><p class="card-text">{{profile.bio}}.</p></div>
            <div class="text-center mt-4">
                <a href="" class="btn btn-warning">Edit profilefile</a>
                <a href="" class="btn btn-danger">Logout</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/Condidates/registration.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
<!-- templates/registration/register.html -->

    
    {% block title %}Register{% endblock  %}

    {% block content %}
    <div class="container-fluid">
        <h2>Register</h2>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit">Register</button>
    </form>{% endblock  %}
    </div>

    