Account/urls.py
from django.urls import path,re_path
from Account import views
from django.views.generic import RedirectView
app_name='Account'

urlpatterns = [
    # path('home/',views.home,name='home'),
    path('signup/',views.SignUpView.as_view(),name='signup'),
    # path('signup/',views.registration_view,name='singup'),
    path('recruitersignup/',views.recruitersignup.as_view(), name='recruitersignup'),
    path('candidatesignup/',views.candidatesignup.as_view(), name='candidatesignup'),
    path('signin/',views.login_view,name='signin'),
    path('signout/',views.logout_view,name='signout'),
    # path('profile_view/',views.profile_view,name='profile'),
    path('candidate_profile/',views.candidate_profile_view,name='candidate_profile'),
    path('profile/update/',views.update_candidate_profile,name='update_candidate_profile'),
    path('recruiter_profile/', views.recruiter_profile_view, name='recruiter_profile'),
    path('profile/update/', views.update_recruiter_profile, name='update_recruiter_profile'),
    
]

JobApp/urls.py
from django.urls import path,re_path
from JobApp import views
from django.views.generic import RedirectView
app_name='JobApp'

urlpatterns = [
    
    path('import_jobs/', views.import_jobs, name='import_jobs'),
    path('', views.job_view, name='job_view'), # if using class based view, views.job_view.as_view()
    path('job-details/<int:job_id>/', views.job_details, name='job_details'),
    path('single_job_view/<int:id>/', views.single_job_view, name='single_job_view'),
    path('apply_job_view/<int:id>/', views.apply_job_view, name='apply_job'),
    path('post_resume', views.post_resume, name='post_resume'),
    path('bookmark_view/<int:id>/', views.bookmark_view, name='bookmark_view'),
    path('create_job/', views.create_job, name='create_job'),
    path('search_job/', views.search_job, name='search_job'),
    path('do_comment/<int:id>/', views.do_comment, name='do_comment'),
    path('likes/<int:id>/',views.like_view,name='likes'),

    # path('commentView/', views.Comments_view.as_view(), name='comment'),
    # path('comment/<int:pk>', views.Comments_view.as_view(), name='comment'),   # get single record 
    # path('comment/<int:id>/', views.comment, name='Commit'),

    



    

    path('dashboard_view/', views.dashboard_view, name='dashboard_view'), 
    path('dashboard/employer/edit_job/<int:id>', views.edit_job, name='edit_job'),
    path('dashboard/employer/delete_job/<int:id>', views.delete_job, name='delete_job'),
    path('dashboard/employer/close/<int:id>', views.make_close_job, name='make_close_job'),
    path('dashboard/employer/delete_bookmark/<int:id>', views.delete_bookmark, name='delete_bookmark'),
    path('dashboard/employer/applicant_details/<int:id>', views.applicant_details, name='applicant_details'),
    path('dashboard/employer/applicants_list/<int:id>', views.applicants_list, name='applicants_list'),


    path('recruiter_job_view/', views.recruiter_job_view, name='recruiter_job_view'),
    path('about_us/', views.about_us, name='about_us'), 
    path('contact_us/', views.contact_us, name='contact_us'), 
    path('custom_csrf_failure/',views.custom_csrf_failure), 
]

job_portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from JobApp.views import job_view 


urlpatterns = [
    path('', job_view, name='job_view'),
    path('admin/', admin.site.urls),
    path('Account/',include('Account.urls')),
    path('JobApp/',include('JobApp.urls')),
    path('',include('jsonApp.urls')),
    path('__reload__/',include('django_browser_reload.urls')),

    
     # Redirect the root URL to the admin page
    
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}
        {% endblock  %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
   
    {% block content %}
    {% endblock  %}

    
    </body>
</html>

templates/candidate_navbar.html
<style>
  /* Fix the navbar to the top */
.navbar.fixed-top {
  position: fixed;
  top: 0;
  left: 0;

  z-index: 1000; /* Bootstrap default z-index for fixed elements */
}
body {
  padding-top: 56px; /* Adjust this value based on your navbar height */
}
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">Job Portal</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'JobApp:job_view' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'JobApp:dashboard_view' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin/">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'JobApp:about_us' %}">About us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'JobApp:contact_us' %}">Contact us</a>
        </li>
        
        
      </ul>
      <ul class="nav navbar-nav navbar-right mr-1">
        {% if user.is_authenticated %}
            
         <!-- Check user type and show the appropriate profile link -->
         {% comment %} {% if user.user_type == 'candidate' %}
         <li><a href="{% url 'Account:candidate_profile' %}">Candidate/</a></li>
     {% elif user.user_type == 'recruiter' %}
         <li><a href="{% url 'Account:recruiter_profile' %}">Recruiter/</a></li>
     {% endif %} {% endcomment %}
     
     <!-- Other links common to both user types --> 
        <li class="nav-item d-flex justify-content-center">
          <a href="{% url 'Account:candidate_profile' %}" class="nav-link"> {{ request.user }}</a> <a href="{% url 'Account:signout' %}" class="nav-link"> logout</a>
        </li>
        {% else %}
        
      <li class="nav-item">
        <a href="{% url 'Account:signup' %}" class="nav-link"> Sign Up</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'Account:signin' %}" class="nav-link"> Sign in</a>
      </li>
      
        {% endif %} 
        <li class=" nav-item "><a href="" class="nav-link"> |</a></li>
        <li class="nav-item">
          <a href="{% url 'JobApp:recruiter_job_view' %}" class="nav-link">Employer / Job post</a>
        </li>
      </ul>
      
    </div>
  </nav>

templates/comment.html
{% load crispy_forms_tags %}
{% load static %}

<form action="">
    
     {% csrf_token %}
     {{ form| crispy }}
     <button type="submit"> submit</button>

</form>

{% for x in comments %}
  <h1>Foor loop</h1>
 {{x.comment}}
 {{x.user}}
 {{x.job}}
{% endfor %}
<div id="comments-section">
    <h2>Comments</h2>
    <ul id="comments-list">
        {% for comment in comments %}
            <li><strong>{{ comment.user }}</strong>: {{ comment.text }} <em>({{ comment.created_at }})</em></li>
        {% endfor %}
    </ul>
</div>

<h3>Submit a Comment</h3>
<form id="comment-form" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

templates/csrf_failure.html
<!-- templates/csrf_failure.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSRF Token Verification Failed</title>
</head>
<body>
    <h1>CSRF Token Error</h1>
    <p>Sorry, your form submission could not be processed due to a CSRF token verification failure. Please try again.</p>
</body>
</html>

templates/footer.html
<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="mt-3">
    <!-- Footer -->
    <footer
            class=" text-lg-start text-white"
            style="background-color: #929fba"
            >
      <!-- Grid container -->
      <div class="container p-1 pb-0">
        <!-- Section: Links -->
        <section class="">
          <!--Grid row-->
          <div class="row">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">
                Company name
              </h6>
              <p>
                Here you can use rows and columns to organize your footer
                content. Lorem ipsum dolor sit amet, consectetur adipisicing
                elit.
              </p>
            </div>
            <!-- Grid column -->
  
            <hr class="w-100 clearfix d-md-none" />
  
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
              <p>
                <a class="text-white">MDBootstrap</a>
              </p>
              <p>
                <a class="text-white">MDWordPress</a>
              </p>
              <p>
                <a class="text-white">BrandFlow</a>
              </p>
              <p>
                <a class="text-white">Bootstrap Angular</a>
              </p>
            </div>
            <!-- Grid column -->
  
            <hr class="w-100 clearfix d-md-none" />
  
            <!-- Grid column -->
            <hr class="w-100 clearfix d-md-none" />
  
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
              <p><i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
              <p><i class="fas fa-envelope mr-3"></i> info@gmail.com</p>
              <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
              <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
            </div>
            <!-- Grid column -->
  
            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Follow us</h6>
  
              <!-- Facebook -->
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #3b5998"
                 href="#!"
                 role="button"
                 ><i class="fab fa-facebook-f"></i
                ></a>
  
              <!-- Twitter -->
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #55acee"
                 href="#!"
                 role="button"
                 ><i class="fab fa-twitter"></i
                ></a>
  
              <!-- Google -->
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #dd4b39"
                 href="#!"
                 role="button"
                 ><i class="fab fa-google"></i
                ></a>
  
              <!-- Instagram -->
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #ac2bac"
                 href="#!"
                 role="button"
                 ><i class="fab fa-instagram"></i
                ></a>
  
              <!-- Linkedin -->
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #0082ca"
                 href="#!"
                 role="button"
                 ><i class="fab fa-linkedin-in"></i
                ></a>
              <!-- Github -->
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #333333"
                 href="#!"
                 role="button"
                 ><i class="fab fa-github"></i
                ></a>
            </div>
          </div>
          <!--Grid row-->
        </section>
        <!-- Section: Links -->
      </div>
      <!-- Grid container -->
  
      <!-- Copyright -->
      <div
           class="text-center p-3"
           style="background-color: rgba(0, 0, 0, 0.2)"
           >
        © 2020 Copyright:
        <a class="text-white" href="https://mdbootstrap.com/"
           >MDBootstrap.com</a
          >
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->
  </div>
  <!-- End of .container -->
   

templates/home.html
{% extends "base.html" %}
{% block title %}Home Page {% endblock  %}
{% block content %}
  {% include "candidates/navbar.html" %}
{% endblock  %}

templates/loadjson.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Import JSON Data</title>
</head>
<body>
    <h1>Import JSON Data</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="json_file">
        <button type="submit">Import</button>
    </form>
</body>
</html>

templates/recruiter_navbar.html
<style>
  /* Fix the navbar to the top */
.navbar.fixed-top {
  position: fixed;
  top: 0;
  left: 0;

  z-index: 1000; /* Bootstrap default z-index for fixed elements */
}
body {
  padding-top: 56px; /* Adjust this value based on your navbar height */
}
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">Job Portal</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'JobApp:job_view' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'JobApp:dashboard_view' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin/">Admin</a>{{ forloop.counter }}
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">Post a job</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=""> Find CVs</a>
        </li>
        {% comment %} <li class="nav-item">
          <a class="nav-link" href="{% url 'JobApp:about_us' %}" data-bs-toggle="modal" data-bs-target="#contactModal">About us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'JobApp:contact_us' %}">Contact us</a>
        </li> {% endcomment %}
        {% comment %} <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#contactModal">
          Contact Us
      </button> {% endcomment %}
      
        
        
      </ul>
      <ul class="nav navbar-nav navbar-right mr-1">
        {% if user.is_authenticated %}
            
         <!-- Check user type and show the appropriate profile link -->
         {% comment %} {% if user.user_type == 'candidate' %}
         <li class="nav-item"><a class="nav-link" href="{% url 'Account:candidate_profile' %}">Candidate/</a></li>
     {% elif user.user_type == 'recruiter' %}
         <li class="nav-item"><a class="nav-link" href="{% url 'Account:recruiter_profile' %}">Recruiter/</a></li>
     {% endif %} {% endcomment %}
     
     <!-- Other links common to both user types --> 
        <li class="nav-item d-flex justify-content-center">
          <a href="{% url 'Account:recruiter_profile' %}" class="nav-link"> {{ request.user }}</a> <a href="{% url 'Account:signout' %}" class="nav-link"> logout</a>
        </li>
        {% else %}
        <li class=" nav-item "><a href="" class="nav-link"> |</a></li>
        <li class="nav-item">
          <a href="{% url 'Account:signup' %}" class="nav-link"> Sign Up</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'Account:signin' %}" class="nav-link"> Sign in</a>
        </li>
      
        {% endif %}
        <li class="nav-item">
          <a href="{% url 'JobApp:job_view' %}" class="nav-link">Find job</a>
        </li>
      </ul>
      
    </div>
  </nav>

templates/successjson.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Import Successful</title>
</head>
<body>
    <h1>Import Successful!</h1>
    <p>The JSON data has been successfully imported into the database.</p>
    <a href="/">Go back to import page</a>
</body>
</html>